#format can be "text" or "json" for different output (human or machine readable)
#format: "text"
#checkAsserts checks assertions
testMode: assertion
#testLimit is the number of test sequences to run
# TODO : Increase the limit and sequence depth
testLimit: 500
#seqLen defines how many transactions are in a test sequence
seqLen: 10
#maximum time between generated txs; default is one week
maxTimeDelay: 15778800 # approximately 6 months
#directory to save the corpus; by default is disabled
corpusDir: "corpus"
#deployer is address of the contract deployer (who often is privileged owner, etc.)
deployer: "0x41414141"
#sender is set of addresses transactions may originate from
sender: ["0x42424242", "0x43434343"]